# Install Dependances
apt-get install python-pip
pip install pyttsx
apt-get install espeak
pip install jupyter
pip install gTTS
apt-get install python-pygame
apt-get install portaudio19-dev
pip install tts-watson
apt-get install python-pyaudio
apt-get install caca-utils
apt-get install gccgo
go get github.com/ichinaski/pxl
